### ISSUE TITLE
Possible ROS1 Hash Error

### ISSUE THREAD

**Issue by mastercheco96** [littlebalup/PyPS3tools#10]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/2098651/dump.hex.checklog.txt)
keep getting:
ROS1 Hash : WARNING!
  Size = 0x6FFFE0
1A1E502AAE7609C7E851BD2366FF76BF
  Version = (unknown)
im on CECH-25xx slim

**Comment by littlebalup** [comment]
Nit related to tools issue
