### ISSUE TITLE
Following check(s) returned a WARNING!   009.05   ROS1 Hash

### ISSUE THREAD

**Issue by Angeltite** [littlebalup/PyPS3tools#11]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/2108857/dump.hex.checklog.txt)

Hi, Littlebalup,

I'm getting a warning in ROS1 Hash. Can you help me or guide me on this please.

Thanks a lot

**Comment by littlebalup** [comment]
Not related to the tools
