### ISSUE TITLE
"The system cannot find the path specified"

### ISSUE THREAD

**Issue by ImaNicedude** [littlebalup/PyPS3tools#13]
Hi, I'm a newbie. I'm having an issue where I'm trying to check my patched dump but it keeps telling me that the system cannot find the path specified. Am I doing anything wrong?

**Comment by littlebalup** [comment]
Could you please post a screenshot? Thanks

**Comment by ImaNicedude** [comment]
Hi, thanks for the response but I seemed to have fixed it by installing an
older version of python.
