### ISSUE TITLE
Ps3 ofw 4.82 (CECH-3001A)

### ISSUE THREAD

**Issue by Eatai0001** [littlebalup/PyPS3tools#14]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/2239159/dump.hex.checklog.txt)
Could you tell me if I can use this or not???

**Comment by littlebalup** [comment]
Don't use ps3xploit v1 or v2 on that console! You'll brick it!... if not already done...

However, it's not PyPS3checker related. I closing it.
