### ISSUE TITLE
1 warning is present

### ISSUE THREAD

**Issue by Camsmasher19** [littlebalup/PyPS3tools#16]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/2709846/dump.hex.checklog.txt)
******* Checking CoreOS_region *******
009.01   ROS0 Header : OK
009.02   ROS0 Hash : OK
  Size = 0x6FFFE0
  MD5 = 4674CA6C38D45171F45C48191528E36F
  Version = 4.82 CEX Patched (PS3Xploit v2.0)

009.03   ROS0 unused 0xFF Filled Area : OK
009.04   ROS1 Header : OK
009.05   ROS1 Hash : WARNING!
  Size = 0x6FFFE0
  MD5 = 1A1E502AAE7609C7E851BD2366FF76BF
  Version = (unknown)

**Comment by littlebalup** [comment]
Normal if you missed to update twice to OFW 4.82 before applying PS3Xploit flash.
http://www.psx-place.com/threads/ps3xploit-flash-writer-aka-cfw-installer-supports-all-ps3-fat-models-most-slim-models.16876/
