### ISSUE TITLE
CECHG03 unrecognized (unusual metldr offset)

### ISSUE THREAD

**Issue by kozarovv** [littlebalup/PyPS3tools#17]
PyPS3checker v0.9.x. Check log.

Checked file : E:\_Pobrane\F1_IDPS-HIDDEN.bin

******* Getting flash type *******
  Flash type : NAND (full dump, 256MB)

******* Getting SKU identification datas *******
  idps = 0x05
  metldr0 = 0xE8E0
  metldr1 = 0x0E8A
  bootldr0 = 0x2EF4
  bootldr1 = 0x2EF4
  bootldrsize = 0x2EF80

  Matching SKU : WARNING!
   No matching SKU found!

******* Getting SDK versions *******
  ROS0 : 476.000
  ROS1 : 478.000

******* Checking bootldr_top_region *******
001.01   bootldr0 (Top) : OK
001.02   bootldr1 (Top) : OK
001.03   bootldr Rev key (Top) : OK
001.04   bootldr Statistics (Top) : OK
001.05   bootldr (Top) 0xFF Filled Area : OK

******* Checking Header_Magic *******
002.01   Header Magic 0x00 Filled Area 0 : OK
002.02   Header Magic : OK
002.03   Header Magic 0x00 Filled Area 1 : OK

******* Checking flash_region_table *******
003.01   Flash Region Table Header : OK
003.02   asecure_loader Offset - Length : OK
003.03   asecure_loader Name : OK
003.04   eEID Offset - Length : OK
003.05   eEID Name : OK
003.06   cISD Offset - Length : OK
003.07   cISD Name : OK
003.08   cCSD Offset - Length : OK
003.09   cCSD Name : OK
003.10   trvk_prg Offset - Length : OK
003.11   trvk_prg Name : OK
003.12   trvk_pkg Offset - Length : OK
003.13   trvk_pkg Name : OK
003.14   creserved_0 Offset - Length : OK
003.15   creserved_0 Name : OK
003.16   ros Offset - Length : OK
003.17   ros Name : OK
003.18   cvtrm Offset - Length : OK
003.19   cvtrm Name : OK
003.20   Flash Region Table 0x00 Filled Area : OK

******* Checking asure_loader_region *******
004.01   asecure_loader Header : OK
004.02   metldr Offset : OK
004.03   metldr Length : OK
004.04   metldr Name : OK
004.05   metldr RevKey : OK
004.06   metldr Binary Size : OK
004.07   metldr Statistics : OK
004.08   asecure_loader 0x00 Filled Area : OK

******* Checking eEID_region *******
005.01   eEID Header : OK
005.02   EID0 Offset - Length : OK
005.03   EID1 Offset - Length : OK
005.04   EID2 Offset - Length : OK
005.05   EID3 Offset - Length : OK
005.06   EID4 Offset - Length : OK
005.07   EID5 Offset - Length : OK
005.08   EID0 IDPS0 : OK
005.09   EID0 IDPS1 : OK
005.10   EID0 Static : OK
005.11   EID2 BlockSize/Padding : OK
005.12   EID3 Static0 : OK
005.13   EID3 Static1 : OK
005.14   EID3 Static2 : OK
005.15   EID5 IDPS0 : OK
005.16   EID5 IDPS1 : OK
005.17   EID5 Static : OK
005.18   eEID Region 0xFF Filled Area : OK
005.19   eEID Statistics0 : OK
005.20   eEID Statistics1 : OK

******* Checking cISD_region *******
006.01   cISD Header : OK
006.02   cISD0 Offset - Length : OK
006.03   cISD1 Offset - Length : OK
006.04   cISD2 Offset - Length : OK
006.05   cISD0 0xFF Filled Area : OK
006.06   cISD1 IDLog Header : OK
006.07   cISD1 Semistatic 1 : OK
006.08   cISD1 Semistatic 2 : OK
006.09   cISD1 0xFF Filled Area 0 : OK
006.10   cISD1 Static : OK
006.11   cISD1 Semistatic 3 : OK
006.12   cISD1 0xFF Filled Area 1 : OK
006.13   cISD1 Statistics : OK
006.14   cISD2 : OK
006.15   cISD 0xFF Filled Area : OK

******* Checking cCSD_region *******
007.01   cCSD Header : OK
007.02   cCSD Entry Table : OK
007.03   cCSD 0xFF Filled Area : OK

******* Checking Revokation_region *******
008.00   trvk_prg Region Header : OK
008.01   trvk_prg0 SCE : OK
008.02   trvk_prg0 Hash : OK
  Size = 0x2E0
  MD5 = 37DD8C18FE7FF39B983BC0EE907BE8A6
  Version = 3.42 (from PUP)

008.03   trvk_prg1 SCE : OK
008.04   trvk_prg1 Hash : OK
  Size = 0x2E0
  MD5 = E537DE954DCF25D4DE961DF44549BAF7
  Version = 3.50 (from PUP)

008.00   trvk_pkg Region Header : OK
008.05   trvk_pkg0 SCE : OK
008.07   trvk_pkg1 SCE : OK

******* Checking Unreferenced_Area *******
008.08   unreferenced area 0xFF filled : OK

******* Checking CoreOS_region *******
009.00   ROS Header : OK
009.01   ROS0 Header : OK
009.02   ROS0 Hash : OK
  Size = 0x6FFFE0
  MD5 = 51A7758AA326F54CB431FC59DC68AFD4
  Version = 4.76 CEX/SEX OFW

009.03   ROS1 Header : OK
009.04   ROS1 Hash : OK
  Size = 0x6FFFE0
  MD5 = 9E889471205593CAEBD8B47ED8C1C9B2
  Version = 4.78 CEX/SEX OFW

******* Checking cvtrm_region *******
010.01   cvtrm Header : OK
010.02   cvtrm Header Static 1 : OK
010.03   vtrm Magic 1 : OK
010.05   vtrm Magic 2 : OK
010.07   cvtrm 0x00 Filled Area : OK

******* Checking cell_ext_os_area *******
011.01   cell_ext_os_area Header : OK
011.02   cell_ext_os_area 0xFF Filled Area 0 : OK
011.03   cell_ext_os_area Break Section : OK
011.04   cell_ext_os_area 0xFF Filled Area 1 : OK

******* Checking bootldr_bottom_region *******
012.01   bootldr0 (Bottom) : OK
012.02   bootldr1 (Bottom) : OK
012.03   bootldr Rev key (Bottom) : OK
012.04   bootldr Statistics (Bottom) : OK
012.05   bootldr 0xFF Filled Area : OK

******* Checking datamatches *******
bootldr size : OK
per console nonce : OK
bootldr : OK
metldr size : OK
vtrm header datas : OK
vtrm : OK

******* Checking repetitions *******
Header Magic Repetition : OK
asecure_loader Repetition : OK
eEID Repetition : OK
cISD Repetition : OK
cCSD Repetition : OK
trvk_prg Repetition : OK
trvk_pkg Repetition : OK
ros Repetition : OK
cvtrm Repetition : OK

******* Additional information *******
MAC address : xxx
CID : 0x0xxx
eCID : xxx
board_id (part of console S/N) : xxx
kiban_id (board barcode) : xxx

******* Checks completed *******

Total number of checks = 131
Number of dangers = 0
Number of warnings = 1

Following check(s) returned a WARNING!
  SKU identification

All checks done in 3.80 seconds.

**Comment by littlebalup** [comment]
You probably have a refurbished console.
In most cases refurbished consoles have an updated metldr and bootldr not matching those installed originally. In your case it matches values seen on first NOR FAT consoles (DIA-001/002 boards). That's why the warning.
You edited your CID (aka Customer ID. It's not the IDPS / PSID, no need to edit it...) in the  "Additional information". So I can't confirm it.
A CID like 0x0001xxxxxxxx or 0x0002xxxxxxxx means not refurbished.
A CID like 0x0FFFxxxxxxxx means refurbished.

Please check and let me know. Thx.

**Comment by kozarovv** [comment]
CID is starting with 0x0FFF, so refubrished. Thanks for explaining. :)
