### ISSUE TITLE
EMMC MODEL NAME WRONG

### ISSUE THREAD

**Issue by aeri** [littlebalup/PyPS3tools#2]
I have a **_CECH-4004A_** and the checker gives me that:

Matching SKU : OK
**CECH-42xxA (NPX-001 or PQX-001)**
Minimum version 4.22
WARNING: The machine this dump belongs to is currently not downgradeable!

And it is not true.

But the flash type is correct:

**Flash type : EMMC_PS3Xploit**

Thanks for the tools and good work.

//Deleted checklog for privacy, i can send you secretly.

**Comment by littlebalup** [comment]
Could send your log, then use minerchk pup and give your real minimum version?
Thx

**Comment by alivastac** [comment]
Update data version 4.22 or later can be installed.

[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/1674126/dump.hex.checklog.txt)

**Comment by littlebalup** [comment]
hum... seems both 40xxA and 42xxA can have the same model code (0x0E)... probably because the same mobo. fortunatly it seems to have both minimum version 4.22
So, waiting more dumps for comparison, i'll have to set 
CECH-4xxxA
Minimum version 4.22

Thank you for the heads-up
