### ISSUE TITLE
ps3 4201a

### ISSUE THREAD

**Issue by DYRM3006** [littlebalup/PyPS3tools#21]
____        ____  ____ _____      _               _
 |  _ \ _   _|  _ \/ ___|___ /  ___| |__   ___  ___| | _____ _ __
 | |_) | | | | |_) \___ \ |_ \ / __| '_ \ / _ \/ __| |/ / _ \ '__|
 |  __/| |_| |  __/ ___) |__) | (__| | | |  __/ (__|   <  __/ |
 |_|    \__, |_|   |____/____/ \___|_| |_|\___|\___|_|\_\___|_|
        |___/                                               v0.10.x

 Python checker script for PS3 flash memory dump files
 Copyright (C) 2015 littlebalup@gmail.com

Loading file "E:\PICTURE\2019-05\dump.jpg" to memory...  Done

******* Getting flash type *******
  Flash type : EMMC (partial dump, 239MB)

******* Getting SKU identification datas *******
  idps = 0x12
  metldr0 = 0xF9B0
  metldr1 = 0x0F97
  metldrkey = 0xB233329B8D28B967C65E2097

  Matching SKU : OK
   CECH-42xxA (PPX-001 or PQX-001)
   Minimum version 4.40
 WARNING: The machine this dump belongs to is currently not downgradeable!

******* Getting SDK versions *******
  ROS0 : 484.000
  ROS1 : 484.000

******* Checking Header_Magic *******
002.01   Header Magic 0x00 Filled Area 0 : OK
002.02   Header Magic : OK
002.03   Header Magic 0x00 Filled Area 1 : OK

******* Checking flash_region_table *******
003.01   Flash Region Table Header : OK
003.02   asecure_loader Offset - Length : OK
003.03   asecure_loader Name : OK
003.04   eEID Offset - Length : OK
003.05   eEID Name : OK
003.06   cISD Offset - Length : OK
003.07   cISD Name : OK
003.08   cCSD Offset - Length : OK
003.09   cCSD Name : OK
003.10   trvk_prg Offset - Length : OK
003.11   trvk_prg Name : OK
003.12   trvk_pkg Offset - Length : OK
003.13   trvk_pkg Name : OK
003.14   creserved_0 Offset - Length : OK
003.15   creserved_0 Name : OK
003.16   ros Offset - Length : OK
003.17   ros Name : OK
003.18   cvtrm Offset - Length : OK
003.19   cvtrm Name : OK
003.20   Flash Region Table 0x00 Filled Area : OK

******* Checking asure_loader_region *******
004.01   asecure_loader Header : OK
004.02   metldr Offset : OK
004.03   metldr Length : OK
004.04   metldr Name : OK
004.05   metldr RevKey : OK
004.06   metldr Binary Size : OK
004.07   metldr Statistics : OK
004.08   asecure_loader 0x00 Filled Area : OK

******* Checking eEID_region *******
005.01   eEID Header : OK
005.02   EID0 Offset - Length : OK
005.03   EID1 Offset - Length : OK
005.04   EID2 Offset - Length : OK
005.05   EID3 Offset - Length : OK
005.06   EID4 Offset - Length : OK
005.07   EID5 Offset - Length : OK
005.08   EID0 IDPS0 : OK
005.09   EID0 IDPS1 : OK
005.10   EID0 Static : OK
005.11   EID2 BlockSize/Padding : OK
005.12   EID3 Static0 : OK
005.13   EID3 Static1 : OK
005.14   EID3 Static2 : OK
005.15   EID5 IDPS0 : OK
005.16   EID5 IDPS1 : OK
005.17   EID5 Static : OK
005.18   eEID Region 0xFF Filled Area : OK
005.19   eEID Statistics0 : OK
005.20   eEID Statistics1 : OK

******* Checking cISD_region *******
006.01   cISD Header : OK
006.02   cISD0 Offset - Length : OK
006.03   cISD1 Offset - Length : OK
006.04   cISD2 Offset - Length : OK
006.05   cISD0 0xFF Filled Area : OK
006.06   cISD1 IDLog Header : OK
006.07   cISD1 Semistatic 1 : OK
006.08   cISD1 Semistatic 2 : OK
006.09   cISD1 0xFF Filled Area 0 : OK
006.10   cISD1 Static : OK
006.11   cISD1 Semistatic 3 : OK
006.12   cISD1 0xFF Filled Area 1 : OK
006.13   cISD1 Statistics : OK
006.14   cISD2 : OK
006.15   cISD 0xFF Filled Area : OK

******* Checking cCSD_region *******
007.01   cCSD Header : OK
007.02   cCSD Entry Table : OK
007.03   cCSD 0xFF Filled Area : OK

******* Checking Revokation_region *******
008.00   trvk_prg Region Header : OK
008.01   trvk_prg0 SCE : OK
008.02   trvk_prg0 Hash : OK
  Size = 0x2E0
  MD5 = 43252D7C42C07AC7DE48EEDEA23015EC
  Version = 4.40 (from factory)

008.03   trvk_prg1 unused area : OK
008.00   trvk_pkg Region Header : OK
008.05   trvk_pkg0 SCE : OK
008.03   trvk_pkg1 unused area : OK

******* Checking Unreferenced_Area *******
008.08   unreferenced area 0xFF filled : OK

******* Checking CoreOS_region *******
009.00   ROS Header : OK
009.01   ROS0 Header : OK
009.02   ROS0 Hash : OK
  Size = 0x6FFFE0
  MD5 = E2396DD395E095128BCB69AABA2D1978
  Version = 4.84 CEX/SEX OFW

009.03   ROS1 Header : OK
009.04   ROS1 Hash : OK
  Size = 0x6FFFE0
  MD5 = E2396DD395E095128BCB69AABA2D1978
  Version = 4.84 CEX/SEX OFW

******* Checking cvtrm_region *******
010.02   cvtrm0 Header : OK
010.03   cvtrm0 0xFF Filled Area : OK
010.04   vtrm0 Magic : OK
010.05   vtrm0 Reserved Entries : OK
010.07   cvtrm1 Header : OK
010.08   cvtrm1 0xFF Filled Area : OK
010.09   vtrm1 Magic : OK
010.10   vtrm1 Reserved Entries : OK

******* Checking datamatches *******
per console nonce : OK
metldr size : OK
vtrm0 : OK
vtrm1 : OK

******* Checking repetitions *******
Header Magic Repetition : OK
asecure_loader Repetition : OK
eEID Repetition : OK
cISD Repetition : OK
cCSD Repetition : OK
trvk_prg Repetition : OK
trvk_pkg Repetition : OK
ros Repetition : OK
cvtrm Repetition : OK

******* Additional information *******
MAC address : F8:D0:AC:F7:A2:C0
CID : 0x0002046414E9
eCID : 01DF04A6412437180F047C4200000010
board_id (part of console S/N) : 27445983
kiban_id (board barcode) : 403101211262

******* Checks completed *******

Total number of checks = 111
Number of dangers = 0
Number of warnings = 1

Following check(s) returned a WARNING!
  SKU identification

All checks done in 17.20 seconds.

 ----------------------------------------------------------------------------
| IMPORTANT NOTICE !                                                         |
| Checks of late CECH-25xxx, CECH-3xxxx and CECH-4xxxx consoles dumps still  |
| under development and may return false results. If you feel it's the case, |
| please post your *.checklog.txt in a new issue on my github repository:    |
|   https://github.com/littlebalup/PyPS3tools/issues                         |
| Thanks! It will help me a lot to improve that tool ;)                      |
 ----------------------------------------------------------------------------

This window will be closed. Do you want to open the log file? [Y,N]?Terminate batch job (Y/N)?

**Comment by littlebalup** [comment]
warning is due to : "WARNING: The machine this dump belongs to is currently not downgradeable!"
means that console can't be dowgraded.
