### ISSUE TITLE
0 Dangers   1 Warnings "SKU identification"    CECH-2504A

### ISSUE THREAD

**Issue by LekkereBoyke** [littlebalup/PyPS3tools#23]
can i continue with this warning?

[dump_patched.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/3318831/dump_patched.hex.checklog.txt)

**Comment by littlebalup** [comment]
Yes. That warning is just to notify your console is 3.56 so it can't be downgraded to 3.55 for FSM method (old school method). You can jailbreak via PS3xploit.
