### ISSUE TITLE
Here is my dump file log 

### ISSUE THREAD

**Issue by moses-dz** [littlebalup/PyPS3tools#28]
my log file is on comments if you're happy to check it :)
help me please

[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/4485898/dump.hex.checklog.txt)

**Comment by moses-dz** [comment]
the problem is that it is not supported, any help ??

**Comment by littlebalup** [comment]
The warning means your console model can't be jailbroken. Means you can't downgrade, you can't install a CFW.
But there is an altenative that's HEN (Homebrew ENabler) provided by the PS3xploit team.

**Comment by moses-dz** [comment]
Thank you if you can explain to me how HEN enabler work and what it can do ???
thanks again.../

**Comment by moses-dz** [comment]
but my OFW is 4.86 how can u help me ??
thank you so much.

**Comment by moses-dz** [comment]
please can you tell if i can enable HEN or not

**Comment by littlebalup** [comment]
yes you can
