### ISSUE TITLE
Got 1 danger after test, could I still jailbreak it ?

### ISSUE THREAD

**Issue by imjayge** [littlebalup/PyPS3tools#29]
Hi,
My PS3 is the fat one.

PS3 Model: CECHL07
Firmware version: 4.85

After running this check I got 1 danger. Could I still JB it?

Below is my check log:
[https://www.dropbox.com/s/mi3lnalckyxujmx/dump.hex.checklog_martin.txt?dl=0](url)

Thanks.

**Comment by littlebalup** [comment]
Hi,
It looks like your console has been refurbished by Sony. Your cISD is not common and returns a false negative. I need to add it to the checker. 

Yes you can JB without problem.

In add, please process this : https://www.psx-place.com/threads/need-community-help-to-collect-data.20882/
It will help to confirm your PS3 is refurbished.
Thanks

**Comment by imjayge** [comment]
Yo~

I've jailbroken correctly. Thanks for your help!
