### ISSUE TITLE
1 Warning after test

### ISSUE THREAD

**Issue by Pietie420** [littlebalup/PyPS3tools#30]
Hello, I received "WARNING! SKU identification" after I ran the test. My ps3 is the slim 25xxB version. Can I sill jailbreak my ps3? My log file is attached.
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/4672408/dump.hex.checklog.txt)

Thank you.

**Comment by littlebalup** [comment]
Hi,
That warning mean your PS3 is **not** compatible for downgrade (aka jailbreak, costom firmware installation). If you try to jailbreak, you'll brick.
Your only option is the ps3xploit hen (**h**omebrew **en**abler).

**Comment by littlebalup** [comment]
Sorry, forget my previous answer. 
Yes you can jailbreak and install any CFW 3.56 or upper version. But you can't downgrade to 3.55.

**Comment by Pietie420** [comment]
Hey, yes I was on CFW 3.56 and the jailbreak was successful.
Thank you.

**Comment by RealTrimm** [comment]
it's what happenend to me

**Comment by RealTrimm** [comment]
"WARNING! SKU identification"  I have proof "WARNING!
