### ISSUE TITLE
Late CECH-25xxx

### ISSUE THREAD

**Issue by BernardoMorais** [littlebalup/PyPS3tools#34]
Hi,

I would like to check about false results on my late(?) CECH-25xxx.

Thanks folks.
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/4991891/dump.hex.checklog.txt)

**Comment by lmunteanu** [comment]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/5826183/dump.hex.checklog.txt)
no errors on my CECH-2504B, but it could help in development

**Comment by thigobras** [comment]
Hi,

I´d like to check about two warnings results on my CECH-2511. Can I proceed?

Thanks guys
[PyPS3checker.changelog.txt](https://github.com/littlebalup/PyPS3tools/files/5877823/PyPS3checker.changelog.txt)
.

**Comment by shabeerps3** [comment]
******* Checks completed *******

Total number of checks = 155
Number of dangers = 0
Number of warnings = 2

Following check(s) returned a WARNING!
  009.02   ROS0 Hash
  009.05   ROS1 Hash

Can I proceed or not? please advise[

[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/5991994/dump.hex.checklog.txt)

**Comment by littlebalup** [comment]
> 
> 
> ******* Checks completed *******
> 
> Total number of checks = 155
> Number of dangers = 0
> Number of warnings = 2
> 
> Following check(s) returned a WARNING!
> 009.02 ROS0 Hash
> 009.05 ROS1 Hash
> 
> Can I proceed or not? please advise[
> 
> [dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/5991994/dump.hex.checklog.txt)

You must update your Pyps3checker. That hash is Evilnat's 4.87 : https://github.com/littlebalup/PyPS3tools/blob/0214a541d9c447359050141095eb1a0b4f337139/PyPS3checker/hashlist.xml#L376
