### ISSUE TITLE
SKU identification

### ISSUE THREAD

**Issue by Menyus73** [littlebalup/PyPS3tools#37]
******* Checks completed *******

Total number of checks = 155
Number of dangers = 0
Number of warnings = 1

Following check(s) returned a WARNING!
  SKU identification
Please help :(

**Comment by littlebalup** [comment]
It may be refurbished console. I'll need your complete log to confirm.

**Comment by Menyus73** [comment]
Here 👍 
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/6473831/dump.hex.checklog.txt)

**Comment by littlebalup** [comment]
> CECH-25xxx (JSD-001 or JTP-001)
   Minimum version 3.60
 WARNING: **The machine this dump belongs to is currently not downgradeable!**

The warning means you can't install a CFW to this machine. Only HEN.

**Comment by Menyus73** [comment]
THX ! HFW ?

**Comment by littlebalup** [comment]
HFW + HEN

**Comment by Menyus73** [comment]
Thank you !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mohameder3** [comment]
******* Checks completed *******

Total number of checks = 155
Number of dangers = 0
Number of warnings = 1
following check resturned warning! sku identification
All checks done in 3.50 seconds

help withe this ps3 4.90 please
