### ISSUE TITLE
its says "Error: Inconsistent indentation detected!"

### ISSUE THREAD

**Issue by mydamnps3** [littlebalup/PyPS3tools#38]
on line 325
`		 	if subnode.tag == "binentry":
`
Sorry I know nothing about programming just signed up here to tell you this
whem i click run module it says "Error: Inconsistent indentation detected!

1) Your indentation is outright incorrect (easy to fix), OR

2) Your indentation mixes tabs and spaces.

To fix case 2, change all tabs to spaces by using Edit->Select All followed by Format->Untabify Region and specify the number of columns used by each tab."

How to fix? First time jailbreaking. DOnt want to go futher without checking my 'dump' as tutorial suggests

**Comment by littlebalup** [comment]
Hopefully, I fixed it in the last commit I just pushed. But that's very strange you obtained that error. What version of python and/or interpreter do you use?

**Comment by mydamnps3** [comment]
After getting syntax error in python3 I installed Python 2.7.18
I'm using macos and compiled it in IDLE

Thank you for your work. I have not tested your corrected version as yet

**Comment by littlebalup** [comment]
Ok. IDLE is not the best to run python script. You should use the Terminal instead. 
https://pythonbasics.org/execute-python-scripts/
