### ISSUE TITLE
Syntax error: invalid syntax

### ISSUE THREAD

**Issue by ranjithran** [littlebalup/PyPS3tools#4]
Line 106 syntax error when checking the ps3 emmc dump 4.82

**Comment by littlebalup** [comment]
It works great on my side using python 2.7.11.
What's your python version? (run the "python --version" command)

**Comment by ranjithran** [comment]
3.6.4

**Comment by ranjithran** [comment]
Tqs little balup it working on 2.7.11 but i have super-slim so u r in under development u need checklog

**Comment by littlebalup** [comment]
You need python 2.7.xx to run those scripts. Please see readme files.

**Comment by littlebalup** [comment]
Python 2 isn't outdated yet...
