### ISSUE TITLE
ROS1 Hash WARNING

### ISSUE THREAD

**Issue by ChaCofymate** [littlebalup/PyPS3tools#43]
I am doing PS3 Jailbreak 4.88 CFW  and I got this warning after checking dump file with pyps3tool: 
 

******* Checking CoreOS_region *******
009.01   ROS0 Header : OK
009.02   ROS0 Hash : OK
  Size = 0x6FFFE0
  MD5 = 36A0D80FB18E9D6FD7635217D59FA726
  Version = 4.88 CEX/SEX OFW/HFW

009.03   ROS0 unused 0xFF Filled Area : OK
009.04   ROS1 Header : OK
009.05   ROS1 Hash : WARNING!
  Size = 0x6FFFE0
  MD5 = 8518C75D4D877A035A9008A7D96FE958
  Version = (unknown)

009.06   ROS1 unused 0xFF Filled Area : OK

******* Checks completed *******

Total number of checks = 155
Number of dangers = 0
Number of warnings = 1

Following check(s) returned a WARNING!
  009.05   ROS1 Hash

All checks done in 3.73 seconds.

Any advice?

**Comment by littlebalup** [comment]
Are you using an hardware flasher or the PS3 toolset? What was the firmware installed before the 4.88 ofw?

**Comment by ChaCofymate** [comment]
Firmware version 3.20 

I am using the the guide base on this one... https://www.youtube.com/watch?v=y2esLWRKLPI

**Comment by littlebalup** [comment]
Ok, so probably an unknown exotic or modified 4.81 CFW was installed before the 4.88 OFW. If you reinstall the 4.88 OFW a second time the warning should disappear.

**Comment by ChaCofymate** [comment]
System did automatically updated few weeks ago and I just finished restoring the Ps3 on its default state (thus removing any previous installed apps) fresh start. 

Any suggestion how I can force reinstall the 4.88 OFW?

**Comment by littlebalup** [comment]
Ok, download the 4.88 official firmware from sony's official site : https://www.playstation.com/en-us/support/hardware/ps3/system-software/
Then install it using the safe mode (system update): https://www.youtube.com/watch?v=TVOJny2FdRM

**Comment by ChaCofymate** [comment]
OMG it WORKS!!!

![image](https://user-images.githubusercontent.com/4745328/132098211-795daea3-c1ad-4523-8ca5-e53466874c8e.png)

Was able to successfully reinstall the 4.88 OFW . Have to ensure that USB was in fat32 format and it works!.... 

Thank you so much! .... Hopefully the installation for this jailbreak will complete without a hitch. 

Have a great day! thanks

**Comment by Hamish336** [comment]
Thanks! This worked for me as well! Installing once through safe mode via usb still gave ROS1 Hash warning. Reinstalling a second time using system update via usb resolved my issues 👍
