### ISSUE TITLE
ERROR: checklist.xml file not found!

### ISSUE THREAD

**Issue by LokiInside** [littlebalup/PyPS3tools#48]
On Big Sur fresh download from GitHub, i done just chmod +x on script.
![Bildschirmfoto 2021-11-05 um 22 56 04](https://user-images.githubusercontent.com/75278757/140583004-8d8f49da-62ac-4970-baba-0ba0c6d3039f.png)

**Comment by littlebalup** [comment]
You must download the whole files : https://github.com/littlebalup/PyPS3tools/tree/master/PyPS3checker
specialy both .xml files must be in the same folder than the .py file.
