### ISSUE TITLE
ps3 jailbreak issue

### ISSUE THREAD

**Issue by wissab** [littlebalup/PyPS3tools#49]
hi, when using pyps3checker there is a warning out there. I updated the console to 4.88 but the same warning appears. 
   

Following check(s) returned a WARNING!
  SKU identification

[dump_orig.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/7618660/dump_orig.hex.checklog.txt)
s/7618657/dump_orig.hex.checklog.txt)

**Comment by littlebalup** [comment]
>   WARNING: Not downgradable to 3.55. NOR must only be patched 4.xx noFSM Patches to install CFW on this machine!

Hi, that's your warning. It says what it says.
