### ISSUE TITLE
trvk_prg0 Hash/ trvk_prg1 Hash Warning on PS3 cech-2511A

### ISSUE THREAD

**Issue by alfredogarza** [littlebalup/PyPS3tools#5]
I'm checking my dump.hex file and these Warning appear:

Following check(s) returned a WARNING!
  008.02     trvk_prg0 Hash
  008.04     trvk_prg1 Hash

Is it safe proceeding with the Xploit?

**Comment by littlebalup** [comment]
Should be fixed since this commit: https://github.com/littlebalup/PyPS3tools/commit/d25845a00ef9c100a9d5c88c3f41fd6aae3f101c
