### ISSUE TITLE
Syntax Error Line 106

### ISSUE THREAD

**Issue by Traace** [littlebalup/PyPS3tools#6]
When I try to run pyPS3checker it gives me syntaxError: invalid syntax. No matter if I use a vaild dump or not

`line 106
    print tab, " ".join(a+b for a,b in zip(chunk[::2], chunk[1::2]))
            ^
SyntaxError: invalid syntax`

Python Version: 3.6.4 32-bit | Env. : Windows 10 64-bit

**Comment by littlebalup** [comment]
https://github.com/littlebalup/PyPS3tools/issues/4
