### ISSUE TITLE
WARNING! SKU identification

### ISSUE THREAD

**Issue by Mistyowl** [littlebalup/PyPS3tools#62]
[dump.hex.checklog.txt](https://github.com/littlebalup/PyPS3tools/files/13247405/dump.hex.checklog.txt)

PS 3 Slim 2***
Date: 0C

**Comment by littlebalup** [comment]
>   Matching SKU : OK
   CECH-25xxx (JSD-001 or JTP-001)
   Minimum version 3.60
 WARNING: The machine this dump belongs to is currently not downgradable!

That warning means you can't install a CFW on that machine. Only HEN.
