### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CAPMAGIC** [littlebalup/PyPS3tools#7]
Hi,

I got the following issue using python 2.7.11

  File "checker.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by mizernika** [comment]
I have the same problem with either of my PC and laptop, running Win7 x64. Tried different Python versions like 2.7, 2.7.11 and so on, but I get the same result. When I get the error, the cmd prompt automatically closes.

**Comment by mizernika** [comment]
Hi again, I figured it out, at least it worked for me. The thing is that you have to uninstall all previous Python versions from control panel and delete all Python folders from C:\ drive. Then do a restart and install Python 2.7.2 but only for current users. Hope it works for you. 
Cheers!
