### ISSUE TITLE
windows defender trojan detected?

### ISSUE THREAD

**Issue by wadeinator74** [littlebalup/PyPS3tools#70]
Not sure if this was just Windows Defender giving me a false positive on a trojan virus but I just wanted to have you guys verify before I disable the anti-virus.  I'm just wary because the file was updated only 9 hours ago. Thank you!
![Untitled](https://github.com/littlebalup/PyPS3tools/assets/25810046/b5175d35-e7fc-478d-a0b6-9512925c392b)

**Comment by littlebalup** [comment]
nothing reported on my side
