### ISSUE TITLE
SKU IDENTIFICATION

### ISSUE THREAD

**Issue by AIABSmonke** [littlebalup/PyPS3tools#71]
Just want a one word answer, Can i use Evilnat 4.91 with this?
The log:
[message.txt](https://github.com/littlebalup/PyPS3tools/files/14706091/message.txt)

**Comment by AIABSmonke** [comment]
Sorry that’s incorrect thisnis the log.
[Uploading ps3log.txt…]()

**Comment by littlebalup** [comment]
https://github.com/littlebalup/PyPS3tools/issues/41
