### ISSUE TITLE
PS3 CECH-2504A DUMP LOG

### ISSUE THREAD

**Issue by KiRZCH** [littlebalup/PyPS3tools#72]
# CECH-2504A DUMP LOG

## Why?

Easy, Littlebalup wrote this at the end of the log:  
```
 ---------------------------------------------------------------------------- 
| IMPORTANT NOTICE !                                                         |
| Checks of late CECH-25xxx, CECH-3xxxx and CECH-4xxxx consoles dumps still  |
| under development and may return false results. If you feel it's the case, |
| please post your *.checklog.txt in a new issue on my github repository:    |
|   https://github.com/littlebalup/PyPS3tools/issues                         |
| Thanks! It will help me a lot to improve that tool ;)                      |
 ---------------------------------------------------------------------------- 
```
My PS3 is **CECH-2504A** so i thought i could help!

## Warnings and Errors

The Hash of the ROS banks is not in the hashlist, so that gives me 2 warnings, I didn't care much 'cause it was matching and i know it's a genuine dump and not corrupted!
ROS Banks Hash: `EFEA4A89E9AB3457103F9A615B323129`
**No errors reported from this dump!**

## Why the dump log says "OK" without warings?

This is just a *"my thing"* and is not mandatory but i simply edited the "hashlist.xml" adding a line with my hash (repeat, 'cause i know is genuine, if you are not sure, don't do that)
like this:
```xml
<!--  CFW/MFW  -->
<hash name=" MY DUMP 4.91 Evilnat Cobra PEX">EFEA4A89E9AB3457103F9A615B323129</hash> <!-- HERE -->
<hash name="4.91 Evilnat Cobra CEX noBD">215437E36A0479253A699C72BAE0EF54</hash>
<hash name="4.91 Evilnat Cobra CEX OC">3CA9277426674C85560BED8DE6469E97</hash>
<hash name="4.91 Evilnat Cobra CEX">0A4632FF4F8127EBD39C7BD92C6E23B1</hash>
<hash name="4.91 Evilnat Cobra D-PEX">5CF158034A0AC4EB00730F674C914820</hash>
<hash name="4.91 Evilnat Cobra DEX">A37F5F16CA08417F385DDF8E4868F75F</hash>
<hash name="4.91 Evilnat Cobra PEX">C2362B79B0128FD4BF3DD74FA167A5CF</hash>
<hash name="4.91 Littlebalup Dual Boot">38F5ADE1EC66092089FE061D2A6C4778</hash>
```

## NOR DUMP

> From my personal NOR.md

- Model: **CECH-2504A**
- Type: **NOR**
- Swapped bytes: **NO**
- Min_ver_check: **3.40**
- Patched: **YES**
    - Method: **Old School E3 Flasher**
    - Patch: **3.55 FSM + RVK PATCH**
- ROS Banks
    - ROS0
        - Header: **0x6FFFE0**
        - Version (xxx\.xxx): **491.000**
        - Hash (MD5): **EFEA4A89E9AB3457103F9A615B323129**
        - Hash Name: **MY DUMP 4.91 Evilnat Cobra PEX**
    - ROS1
        - Header: **0x6FFFE0**
        - Version (xxx\.xxx): **491.000**
        - Hash (MD5): **EFEA4A89E9AB3457103F9A615B323129**
        - Hash Name: **MY DUMP 4.91 Evilnat Cobra PEX**
- File
[FLASH-NOR-FW4.91.bin.checklog.zip](https://github.com/littlebalup/PyPS3tools/files/14780428/FLASH-NOR-FW4.91.bin.checklog.zip)
*Dumped using Evilnat's Utils in the Network column*
*EDIT: Forgot the minisig file 👍*

## Validate log

**Not mandatory** but *"you never know"*
i used this quick signing tool called **Minisign**

1. Install [Minisign](https://jedisct1.github.io/minisign/)
2. Extract the Minisig program and the log file
3. use this command to verify the sign and integrity of the log
```shell
minisign -V -m FLASH-NOR-FW4.91.bin.checklog.txt -P RWRXYLXmrhEkOxH8Kg79e0EzdLH049BBYWsadFdlNbFh7t0jL2DOqKjB
``` 
4. If everything went good you should see a trusted comment: `PS3 NOR DUMP LOG FROM 'PyPS3Checker' (Sensitive infos removed)`

**Comment by littlebalup** [comment]
fixed with latest commit https://github.com/littlebalup/PyPS3tools/commit/44e75c0ef785517d932d83dd7ba8696fdacfa25f
