### ISSUE TITLE
no mac version

### ISSUE THREAD

**Issue by catguy323** [littlebalup/PyPS3tools#76]
i would like there to be a .py or .command version of the .bat files because i use a mac i tried the windows emulators they just dont work

**Comment by TheRealBrodie** [comment]
You can use parelles

**Comment by catguy323** [comment]
> You can use parelles

what is that

**Comment by TheRealBrodie** [comment]
> > You can use parelles
> 
> what is that

something that lets u run windows on mac

**Comment by TheRealBrodie** [comment]
> > > You can use parelles
> > 
> > 
> > what is that
> 
> something that lets u run windows on mac

it works well
